ipSource: https://checkip.amazonaws.com
cacheFile: /etc/cachedexternalip
jokerEndpoint: https://svc.joker.com/nic/update
timeoutSeconds: 15
user: joker-user
password: placeholder
updates:
  - example.com
  - mirror.example.com
  - ssh.example.com
