jokerEndpoint: https://svc.joker.com/nic/update
timeoutSeconds: 15
user: joker-user-xxxx
password: placeholder-password
hosts:
  - dublinux.net
  - mirror.dublinux.net
  - ssh.dublinux.net
  - netnanny.dublinux.net
  - jellyfin.dublinux.net
