# Joker Dynamic DNS updater configuration (keep a real file outside version control, e.g. /etc/joker.yaml).
ipSource: https://checkip.amazonaws.com
cacheFile: /etc/cachedexternalip
jokerEndpoint: https://svc.joker.com/nic/update
timeoutSeconds: 15
updates:
  - user: 17e7444298b0ac73
    password: 2eff408ed360f82d
    hostname: dublinux.net
  - user: 17e7444298b0ac73
    password: 2eff408ed360f82d
    hostname: mirror.dublinux.net
  - user: 17e7444298b0ac73
    password: 2eff408ed360f82d
    hostname: ssh.dublinux.net
  - user: 17e7444298b0ac73
    password: 2eff408ed360f82d
    hostname: netnanny.dublinux.net
  - user: 17e7444298b0ac73
    password: 2eff408ed360f82d
    hostname: jellyfin.dublinux.net
